### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by farnoy** [renderedtext/semaphore-docs-new#124]
Why is 90% of the API read only? Where are methods for creating projects, like `POST /api/v1/projects`. Are they unimplemented or undocumented? As far as I can tell, you can only create builds,rebuilds and hooks :cry:

**Comment by strika** [comment]
You are right, our API currently doesn't support creating projects. We are in the process of designing a new API, so it would be great if you can send us a support request and describe your use case. We would love to hear what do you think our API needs to support a real live use case. Thanks.

**Comment by farnoy** [comment]
Should I close this ticket now that I sent you a feedback through the site?

**Comment by strika** [comment]
I'll close it. Thanks for the feedback!
