### ISSUE TITLE
rails database docs typo

### ISSUE THREAD

**Issue by jjb** [renderedtext/semaphore-docs-new#376]
here: https://github.com/renderedtext/semaphore-docs-new/blob/master/source/docs/languages/ruby/using-database-in-ruby-application.md

I'm not sure what this means:

> In case a database engine in selected in project settings

should it be "**isn't** selected"?

Thanks!

**Comment by markoa** [comment]
Hi @jjb,

To rephrase it means "When you select a database engine in project settings, then Semaphore generates a `config/database.yml`". If you don't then it doesn't happen. But the engines are still there. :)

Selecting means having chosen something that's not "Don't generate" here:

![screen shot 2017-05-24 at 6 57 53 pm](https://cloud.githubusercontent.com/assets/8651/26415477/ec224980-40b2-11e7-94c6-c568f13a2e76.png)

Does that make sense?

**Comment by jjb** [comment]
gotcha

so, i think it should be **is** selected and not **in** selected? :)

Also I think it would be more typical english to be "When a database engine is selected" or "If a database engine is selected"

(or maybe i'm still confused)

**Comment by markoa** [comment]
I only realized it's **in** and not **is** now that you wrote it the second time. :) Corrected.

**Comment by jjb** [comment]
🌮
