### ISSUE TITLE
Logo should link to Docs Home, not Semaphore Home

### ISSUE THREAD

**Issue by ropsii** [renderedtext/semaphore-docs-new#392]
Clicking this should go to Docs index.
<img width="256" alt="screen shot 2017-06-19 at 12 13 25 pm" src="https://user-images.githubusercontent.com/1923393/27282640-c3dd25d6-54e8-11e7-8fb2-63ba2510dbe5.png">

In order to allow Back to Semaphore homepage we have this link in menu here:
<img width="292" alt="screen shot 2017-06-19 at 12 13 35 pm" src="https://user-images.githubusercontent.com/1923393/27282672-def6e1e0-54e8-11e7-94e1-408d086e6802.png">

Thanks.

**Comment by ijovan** [comment]
Fixed.
