### ISSUE TITLE
GCR instructions leave out role

### ISSUE THREAD

**Issue by atombender** [renderedtext/semaphore-docs-new#480]
"Setting up continuous delivery with Google Container Registry" shows the old Google Cloud UI. The new UI expects you to choose a role for the serivce account. It's not obvious what the role, given that there are no dedicated Container Registry roles. (Last I checked, you needed one or more Storage roles.)

**Comment by nikolalsvk** [comment]
Fixed with https://github.com/renderedtext/semaphore-docs-new/pull/482
